public enum RelacaoFases
{
    brinquedos,
    cores,
    coresComLegenda,
    cuidarPlantas,
    diferente,
    diferenteParaClique,
    exemplo,
    exemplotrocado,
    formas,
    objetos,
    partescorpo,
    pintarfrutas,
    reciclagemFase02,
    reciclagemFase1,
    timesFase1,
    timesFase2,
}
